# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/CW305_designstart.xdc

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# Block Designs: bd/block_diagram/m3_for_arty_a7.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7 || ORIG_REF_NAME==m3_for_arty_a7} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_i_inv_dbgresetn_0/m3_for_arty_a7_i_inv_dbgresetn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_inv_dbgresetn_0 || ORIG_REF_NAME==m3_for_arty_a7_i_inv_dbgresetn_0} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_i_inv_sysresetn1_0/m3_for_arty_a7_i_inv_sysresetn1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_i_inv_sysresetn1_0 || ORIG_REF_NAME==m3_for_arty_a7_i_inv_sysresetn1_0} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_xlconstant_1_0/m3_for_arty_a7_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_1_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_1_0} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_axi_bram_ctrl_0_0/m3_for_arty_a7_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_bram_ctrl_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_axi_interconnect_0_0/m3_for_arty_a7_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_interconnect_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_uartlite_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_blk_mem_gen_0_0/m3_for_arty_a7_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_blk_mem_gen_0_0 || ORIG_REF_NAME==m3_for_arty_a7_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_xlconcat_0_0/m3_for_arty_a7_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconcat_0_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconcat_0_0} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_xlconstant_1_1/m3_for_arty_a7_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_1_1 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_1_1} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_Cortex_M3_0_0/m3_for_arty_a7_Cortex_M3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Cortex_M3_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Cortex_M3_0_0} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_2/m3_for_arty_a7_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_2 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_2} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_xlconstant_1_2/m3_for_arty_a7_xlconstant_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_1_2 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_1_2} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_xlconstant_2_0/m3_for_arty_a7_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_2_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_2_0} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_xlconstant_2_1/m3_for_arty_a7_xlconstant_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_2_1 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_2_1} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_xlconstant_2_2/m3_for_arty_a7_xlconstant_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_2_2 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_2_2} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_xlconstant_5_0/m3_for_arty_a7_xlconstant_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_5_0 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_5_0} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_xlconstant_5_1/m3_for_arty_a7_xlconstant_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xlconstant_5_1 || ORIG_REF_NAME==m3_for_arty_a7_xlconstant_5_1} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_xbar_0/m3_for_arty_a7_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_xbar_0 || ORIG_REF_NAME==m3_for_arty_a7_xbar_0} -quiet] -quiet

# IP: bd/block_diagram/ip/m3_for_arty_a7_auto_pc_0/m3_for_arty_a7_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_auto_pc_0 || ORIG_REF_NAME==m3_for_arty_a7_auto_pc_0} -quiet] -quiet

# XDC: ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_0/clk_wiz_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: bd/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0 || ORIG_REF_NAME==m3_for_arty_a7_proc_sys_reset_base_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/block_diagram/ip/m3_for_arty_a7_proc_sys_reset_base_0/m3_for_arty_a7_proc_sys_reset_base_0_ooc.xdc

# XDC: bd/block_diagram/ip/m3_for_arty_a7_axi_bram_ctrl_0_0/m3_for_arty_a7_axi_bram_ctrl_0_0_ooc.xdc

# XDC: bd/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_uartlite_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0_ooc.xdc

# XDC: bd/block_diagram/ip/m3_for_arty_a7_axi_uartlite_0_0/m3_for_arty_a7_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_uartlite_0_0 || ORIG_REF_NAME==m3_for_arty_a7_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/block_diagram/ip/m3_for_arty_a7_blk_mem_gen_0_0/m3_for_arty_a7_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/block_diagram/ip/m3_for_arty_a7_Cortex_M3_0_0/m3_for_arty_a7_Cortex_M3_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_Cortex_M3_0_0 || ORIG_REF_NAME==m3_for_arty_a7_Cortex_M3_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_2/m3_for_arty_a7_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_2 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_2/m3_for_arty_a7_axi_gpio_0_2_ooc.xdc

# XDC: bd/block_diagram/ip/m3_for_arty_a7_axi_gpio_0_2/m3_for_arty_a7_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==m3_for_arty_a7_axi_gpio_0_2 || ORIG_REF_NAME==m3_for_arty_a7_axi_gpio_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/block_diagram/ip/m3_for_arty_a7_xbar_0/m3_for_arty_a7_xbar_0_ooc.xdc

# XDC: bd/block_diagram/ip/m3_for_arty_a7_auto_pc_0/m3_for_arty_a7_auto_pc_0_ooc.xdc

# XDC: bd/block_diagram/m3_for_arty_a7_ooc.xdc
